# Generated by Django 4.1.7 on 2023-07-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('state', models.CharField(max_length=40)),
                ('plant', models.CharField(max_length=40)),
            ],
        ),
    ]
