# Generated by Django 4.1.7 on 2023-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gytrash',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ownerId', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('icon', models.CharField(max_length=40)),
                ('hunger', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('health', models.IntegerField()),
                ('complicity', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('strength', models.IntegerField()),
            ],
        ),
    ]
