# Generated by Django 4.1.7 on 2023-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_gytrash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
