# Generated by Django 4.1.7 on 2023-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_field_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('lavender', models.JSONField()),
                ('sage', models.JSONField()),
                ('ginger', models.JSONField()),
            ],
        ),
    ]
