# Generated by Django 4.1.7 on 2023-10-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0004_barn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barn',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='barn',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
