# Generated by Django 4.1.7 on 2023-10-07 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0005_remove_barn_owner_id_barn_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barn',
            name='owner',
        ),
        migrations.AddField(
            model_name='barn',
            name='farmer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
