# Generated by Django 4.1.7 on 2023-10-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_field_farmer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='farmer_id',
            new_name='farmer',
        ),
    ]
